### ISSUE TITLE
Hostlist bug

### ISSUE THREAD

**Issue by bgagan911** [jordanpotti/AWSBucketDump#10]
I have a S3 bucket residing with following URL
> http://XXXXX.s3-website-us-east-1.amazonaws.com

Your code makes it 
> http://http://XXXXX.s3-website-us-east-1.amazonaws.com.s3.amazonaws.com

How do I fix this?

**Comment by jordanpotti** [comment]
Your bucket names text file should only contain XXXXXX. Don't put the entire URL's in the bucket names text file, the tool takes a word list and takes care of turning them unto URL's for you.

**Comment by jordanpotti** [comment]
Closing due to lack of response. Hope your figured it out!
