### ISSUE TITLE
No module named xmltodict

### ISSUE THREAD

**Issue by Wayc0des-Land** [jordanpotti/AWSBucketDump#15]
AWSBucketDump.py -h
Traceback (most recent call last):
  File "C:\Python3\AWSBucketDump-master\AWSBucketDump.py", line 15, in <module>
    import xmltodict
ImportError: No module named xmltodict

###################################################################

pip3 install xmltodict
Requirement already satisfied: xmltodict in c:\python3\lib\site-packages (0.11.0)

**Comment by jordanpotti** [comment]
Make sure you are running the tool with Python3.

**Comment by Wayc0des-Land** [comment]
im using python3 for that

C:\Python3\AWSBucketDump-master>pip3 install -r requirements.txt
Requirement already satisfied: certifi==2017.7.27.1 in c:\python3\lib\site-packages (from -r requirements.txt (line 1)) (2017.7.27.1)
Requirement already satisfied: chardet==3.0.4 in c:\python3\lib\site-packages (from -r requirements.txt (line 2)) (3.0.4)
Requirement already satisfied: idna==2.6 in c:\python3\lib\site-packages (from -r requirements.txt (line 3)) (2.6)
Requirement already satisfied: requests==2.20.0 in c:\python3\lib\site-packages (from -r requirements.txt (line 4)) (2.20.0)
Requirement already satisfied: urllib3==1.22 in c:\python3\lib\site-packages (from -r requirements.txt (line 5)) (1.22)
Requirement already satisfied: xmltodict==0.11.0 in c:\python3\lib\site-packages (from -r requirements.txt (line 6)) (0.11.0)

C:\Python3\AWSBucketDump-master>AWSBucketDump.py -h
Traceback (most recent call last):
  File "C:\Python3\AWSBucketDump-master\AWSBucketDump.py", line 15, in <module>
    import xmltodict
ImportError: No module named xmltodict

C:\Python3\AWSBucketDump-master>pip3 install xmltodict
Requirement already satisfied: xmltodict in c:\python3\lib\site-packages (0.11.0)

C:\Python3\AWSBucketDump-master>AWSBucketDump.py -h
Traceback (most recent call last):
  File "C:\Python3\AWSBucketDump-master\AWSBucketDump.py", line 15, in <module>
    import xmltodict
ImportError: No module named xmltodict

C:\Python3\AWSBucketDump-master>

**Comment by jordanpotti** [comment]
Right, but are you running awsbucketdump with python3? It looks like you are running it with whatever version of python is in your path which could be python2. Try to run it with `c:\Python3\python.exe AWSBucketDump.py -h`

**Comment by Wayc0des-Land** [comment]
its worked

thank you @jordanpotti :)
